server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 43.143.68.39:8848
  application:
    name: api-passenger
  redis:
    host: 43.143.68.39
    port: 6379
    database: 0
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 0
    timeout: 2000
    password: 123456